# Generated by Django 4.1.1 on 2023-10-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dpi', models.IntegerField()),
                ('fecha_nacimiento', models.CharField(max_length=10)),
                ('telefono', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='alumnos')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'UsuarioAlumno',
                'verbose_name_plural': 'UsuariosAlumnos',
            },
        ),
        migrations.CreateModel(
            name='UsuarioProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dpi', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='profesores')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'UsuarioProfesor',
                'verbose_name_plural': 'UsuariosProfesores',
            },
        ),
    ]
