# Generated by Django 4.1.1 on 2023-10-13 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_remove_usuarioalumno_username_usuarioalumno_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarioalumno',
            options={'verbose_name': 'Usuario Alumno', 'verbose_name_plural': 'Usuarios Alumnos'},
        ),
        migrations.AlterModelOptions(
            name='usuarioprofesor',
            options={'verbose_name': 'Usuario Profesor', 'verbose_name_plural': 'Usuarios Profesores'},
        ),
    ]
