# Generated by Django 4.1.1 on 2023-10-12 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacioncurso',
            old_name='asignacion_id',
            new_name='asignacion',
        ),
        migrations.RenameField(
            model_name='asignacioncurso',
            old_name='curso_id',
            new_name='curso',
        ),
    ]
