# Generated by Django 4.1.1 on 2023-10-05 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cursos')),
                ('precio', models.FloatField()),
                ('cupo', models.IntegerField()),
                ('disponibilidad', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
            },
        ),
        migrations.AlterModelOptions(
            name='areacurso',
            options={'verbose_name': 'AreaCurso', 'verbose_name_plural': 'AreaCursos'},
        ),
        migrations.DeleteModel(
            name='Cursos',
        ),
        migrations.AddField(
            model_name='curso',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.areacurso'),
        ),
    ]
