# Generated by Django 4.1.1 on 2023-10-09 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_alter_curso_precio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areacurso',
            options={'verbose_name': 'AreaCurso', 'verbose_name_plural': 'AreasCursos'},
        ),
    ]
