# Generated by Django 4.1.1 on 2023-10-11 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_areacurso_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areacurso',
            options={'verbose_name': 'areaCurso', 'verbose_name_plural': 'areasCursos'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
    ]
