# Generated by Django 4.1.1 on 2023-10-14 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0005_alter_areacurso_options_alter_curso_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='cupo',
        ),
        migrations.CreateModel(
            name='AsignacionAlumnoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Asignación curso',
                'verbose_name_plural': 'Asignaciones cursos',
                'unique_together': {('alumno', 'curso')},
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='alumnos',
            field=models.ManyToManyField(through='cursos.AsignacionAlumnoCurso', to=settings.AUTH_USER_MODEL),
        ),
    ]
