# Generated by Django 4.1.1 on 2023-10-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_asignacionalumnocurso_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionalumnocurso',
            name='nombre_alumno',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='asignacionalumnocurso',
            name='nombre_curso',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
