# Generated by Django 4.1.1 on 2023-10-16 00:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_asignacionalumnocurso_nombre_alumno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionalumnocurso',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='asignacionalumnocurso',
            name='updated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
